name: car_route_app
description: "A simple mobile app to estimate distance, time and find best path to travel via car"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
#  internet_connection_checker_plus: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: fontRegular
      fonts:
        - asset: assets/font/fontRegular.ttf
    - family: fontBold
      fonts:
        - asset: assets/font/fontBold.ttf

